### ISSUE TITLE
a getFlag hook so the component doesn't rerender on any configuration change

### ISSUE THREAD

**Issue by bethcodes** [launchdarkly/react-client-sdk#147]
**Is your feature request related to a problem? Please describe.**
When a component uses `getFlags` in an application that enables streaming, the hook returns an object that contains all the flags. Any change to any flag will cause that component to rerender.

This is particularly bad if that component, or any component downstream of it, performs expensive calculations or makes requests to a server. In the worst case, it can result in synchronized traffic spikes whenever the flag configuration is updated.

**Describe the solution you'd like**
I would like a hook with a signature like `getFlag('flag-name')` that only rerenders the subscribed component when that specific flag changes.

**Describe alternatives you've considered**
I considered writing this hook myself, but using custom unsupported functionality is less nice than being able to use the official SDK.

**Comment by XieX** [comment]
Agreed that this would be a nice addition, it's something we've talked about. There's something similar in the [Vue SDK](https://launchdarkly.github.io/vue-client-sdk/index.html#useLDFlag). Will let you know when we've committed to it. Thanks for opening the issue, gives it more weight!

**Comment by wojtekmaj** [comment]
They way LD context is built will cause components to update on every flag update anyways, but still, useFlag would be a really neat addition. For now, we ended up creating this hook ourselves to save the devs from the hassle of extracting flag on their own.

**Comment by oherik** [comment]
This issue is a couple of years old, but I would like to weigh in here - we've had some issues with spikes in our database, and managed to track it down to certain components re-rendering, and making calls to the server, when any flag was updated. @wojtekmaj would you mind sharing how you set up your hook?

**Comment by wojtekmaj** [comment]
I'm afraid I no longer have access to that codebase. But it wasn't anything fancy and certainly didn't solve the issues you're describing.

**Comment by oherik** [comment]
Alright, appreciate that you took the time to answer anyway, thanks.

**Comment by gethari** [comment]
Is this sdk dead ? what's the best way to use this in 2024 ?

**Comment by joker23** [comment]
Hi - thanks again for the report

We've moved active development of the React SDK to the LaunchDarkly js-core monorepo. The successor package is `@launchdarkly/react-sdk` (v4, released 2026-04-30):

https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react

New issues, including feature requests, should be filed against the js-core repo:

https://github.com/launchdarkly/js-core/issues/new/choose

I'm closing this issue as this issue should be addressed in the new SDK version. If your problem reproduces on `@launchdarkly/react-sdk` v4, please open a new issue against js-core and link back to this one -- we'll pick it up there. Thanks!
